### ISSUE TITLE
Unable to access new data from IPython Notebook

### ISSUE THREAD

**Issue by monstermudder78** [BurntSushi/nflgame#107] opened 2015-01-12 14:54 UTC
I have installed nflgame using pip, and then successfully ran nflgame-update-players. I can run nflgame from the terminal as expected on all data.

Now, when using nflgame with IPython Notebook it is working with all the data that came with the initial download. What I can't access are the games that happened this weekend. If I simply fire up python from the terminal I can pull last nights data, and filter it as expected, but I still cant get to it from IPython Notebook, even though I believe it should have been written to disk?

```
In [63]: game = nflgame.one(2014, 2, "DEN", "IND", kind='POST')
In [70]: print game.players

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-64-771e07268ac2> in <module>()
----> 1 print game.players

AttributeError: 'NoneType' object has no attribute 'players'
```
While troubleshooting this on IRC it was suggested to try and update the schedule, which works from the terminal but fails in IPyNotebook with this error:
```
In [47]: import nflgame.update_sched
In [48]: nflgame.update_sched.run()

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2


usage: -c [-h] [--json-update-file JSON_UPDATE_FILE] [--rebuild] [--year YEAR]
          [--phase {PRE,REG,POST}] [--week WEEK]
-c: error: unrecognized arguments: -f /home/casey/.ipython/profile_default/security/kernel-8a9e8884-6d71-40ae-822b-0c9bb62c59f4.json --IPKernelApp.parent_appname='ipython-notebook' --profile-dir /home/casey/.ipython/profile_default --parent=1
To exit: use 'exit', 'quit', or Ctrl-D.
```

Now, just to add one more layer, everything seems to work fine from the ipython shell, it only seems to be the notebook that is causing issues.

Thanks in advance for any assistance.

**Comment by BurntSushi** [comment] 2015-01-12 15:31
I would not expect `nflgame.update_sched.run()` to work inside of a REPL. It's a command line application.

I'm not really familiar with iPython. The fact that `nflgame.one` is giving you a `None` value simply means that you don't have the updated schedule. If you're just running `nflgame-update-schedule`, then maybe it's already trying to pull from the conference championship and not for the divisional round. You can force it to update for a specific week:

```bash
nflgame-update-schedule --year 2014 --phase POST --week 2
```

Otherwise, I don't really know what the problem is. If running code outside of iPython is working just fine and can access the divisional round games, but the *same exact* code fails in iPython, then I see two possibilities:

1. You have two different versions of `nflgame` installed and for whatever reason, iPython is using version A and everything else is using version B.
2. iPython is doing something weird with Python paths that I don't understand. Maybe `__file__` isn't working? Not sure.

To check for #1, try running this in your terminal:

```bash
[andrew@Liger ~] python2 -c 'import nflgame; print nflgame.__path__'
['/home/andrew/data/projects/nflgame/nflgame']
```

Then try this in your iPython shell that's causing problems:

```python
import nflgame
print nflgame.__path__
```

Do the two paths printed match? If not, then you have two different installs of `nflgame`.

**Comment by monstermudder78** [comment] 2015-01-12 16:01
python shell:
```
>>> print nflgame.__path__
['/usr/local/lib/python2.7/dist-packages/nflgame']
```
ipython shell:
```
In [6]: print nflgame.__path__
['/usr/local/lib/python2.7/dist-packages/nflgame']
```
ipython notebook:
```
In [71]: print nflgame.__path__
['/usr/local/lib/python2.7/dist-packages/nflgame']
```

Now, I can run this from the python shell:
```
>>> game = nflgame.one(2014, 2, "DEN", "IND", kind='POST')
>>> print game.players.passing()
[P.Manning, A.Luck]
```
But when I try and do the same thing from IPyNotebook, immediately following, it fails with the same None value as before. But data that was downloaded on the initial install is accessible from inside IPyNotebook. The disconnect seems to be between new vs. old data. Do any of these ideas make sense:
1. The new games aren't getting written to disk by the python shell, and IPyNotebook can't run the scripts to fetch the data from nfl.com.
-OR-
2. The new games are written to disk in some way that IPyNotebook can't access the data,  and IPyNotebook can't run the scripts to fetch the data from nfl.com.

Either way, it seems the new data is somehow different from the old data AND IPyNotebook can't fetch data from nfl.com.

Or I'm way off track, that is also possible. Thanks!

**Comment by BurntSushi** [comment] 2015-01-12 16:09
Yes, it is very possible that new data isn't getting written to disk. Although it is still very strange that iPython would fail and a regular Python shell wouldn't.

In general, it's not a good idea to be installing Python libraries into your system directory. I'd recommend uninstalling it and then re-installing it like so:

```bash
pip install --user nflgame
```

The library will now be in `$HOME/.local` and the scripts that come with `nflgame` will be in `$HOME/.local/bin`.

**Comment by BurntSushi** [comment] 2015-01-12 16:10
(Installing it into your home directory should rule out permission errors from writing the schedule.)

**Comment by monstermudder78** [comment] 2015-01-12 17:46
Ok, so after uninstalling there were 4 .gz files left behind corresponding to this weekends games:
```
casey@Lenovo-G580 /usr/local/lib/python2.7/dist-packages/nflgame/gamecenter-json $ ls
2015011000.json.gz  2015011001.json.gz  2015011100.json.gz  2015011101.json.gz
```
So the data was being written, it just wasn't being accessed by IPyNotebook for some reason.

Now, after reinstalling with `pip install --user nflgame` I have ran into a slew of new problems. `nflgame-update-schedule` doesn't run without using the full path. 

This error now shows up in the python shell, where it would work before.
```
>>> game = nflgame.one(2014, 2, "SEA", "CAR", kind="POST")
>>> print game.players
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'players'
```
And no games are showing up from this weekend, even after updating the schedule.

I am leaning towards going back to the original installation and trying to fight through the IPyNotebook issue, but am willing to keep troubleshooting this --user installation if you think it's worthwhile.

Thanks!

**Comment by BurntSushi** [comment] 2015-01-12 18:56
> Now, after reinstalling with pip install --user nflgame I have ran into a slew of new problems. nflgame-update-schedule doesn't run without using the full path.

Right. You need to add `$HOME/.local/bin` to your `PATH`.

Honestly, I really don't have any idea what's going on. I'm uploading a new version of `nflgame` now to PyPI. In a few minutes, run `pip install --upgrade nflgame` (add `--user` if it's still installed in your `$HOME` directory). Hopefully that will fix things once and for all.

After you upgrade, please make sure you have `nflgame` `1.2.11` installed. (Try `pip list | grep nflgame`.)

**Comment by monstermudder78** [comment] 2015-01-12 20:31
Ok, I have added $HOME/.local/bin to my PATH, and now nflgame-update-players works.

I upgraded to 1.2.11 and verified with `pip list | grep nflgame` .

Here is what I am trying to do and what is/isn't working, maybe looking at the whole process will shed some light on it.

```
casey@Lenovo-G580 ~ $ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nflgame
>>> game = nflgame.one(2014, 17, "SEA", "STL", kind='REG')
>>> print game.players.passing()
[R.Wilson, S.Hill]
>>> 
>>> game = nflgame.one(2014, 2, "DEN", "IND", kind='POST')
>>> print game.players.passing()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'players'
>>>

**Comment by BurntSushi** [comment] 2015-01-12 21:23
I really don't know what's going on. So that's from standard Python right? So it isn't just iPython failing now. It's working OK for me here:

```
>>> import nflgame
>>> game = nflgame.one(2014, 17, "SEA", "STL", kind='REG')
>>> print game.players.passing()
[R.Wilson, S.Hill]
>>> game = nflgame.one(2014, 2, "DEN", "IND", kind='POST')
>>> print game.players.passing()
[P.Manning, A.Luck]
>>> print nflgame.__version__
1.2.11
```

**Comment by BurntSushi** [comment] 2015-01-12 21:25
ipython works fine for me too:

```
[andrew@Liger ~] ipython2 
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import nflgame

In [2]: game = nflgame.one(2014, 2, "DEN", "IND", kind='POST')

In [3]: game.players.passing()
Out[3]: <nflgame.seq.GenPlayerStats at 0x7f7f40fd4250>

In [4]: print game.players.passing()
[P.Manning, A.Luck]

In [5]: print nflgame.__version__
1.2.11
```

**Comment by monstermudder78** [comment] 2015-01-12 21:25
Yes, that was standard python. I went ahead and uninstalled and then did a standard install into /usr and everything seems to be working for now, even the playoff games from yesterday, any chance that data was part of the new 1.2.11 download or did nflgame successfully fetch it?

**Comment by BurntSushi** [comment] 2015-01-12 21:27
Yes. I pushed out a new release because I didn't know how else to fix/debug the problem. :-)

Other people are having issues too. My suspicion is that it's a permissions issue, but that shouldn't happen if you install to `$HOME`. I'll need to figure out a better system next year so people aren't confused when the playoff games don't show up.

**Comment by BurntSushi** [comment] 2015-01-12 21:27
Glad it's working now!

**Closed by BurntSushi** 2015-01-12 21:27 UTC

**Comment by monstermudder78** [comment] 2015-01-12 21:30
Well, thanks for the help, and sorry for being a pain in the ass. This whole nflgame/nfldb project is quite impressive. Keep up the good work and if there is ever anything I could lend a hand with I'd be happy to help.

Thanks again!

**Comment by BurntSushi** [comment] 2015-01-12 21:34
No problem. I'm just happy you got it working! :-) Enjoy!
